### ISSUE TITLE
Leap Frog: Tests for on the Lattice

### ISSUE THREAD

**Issue by flipdazed** [flipdazed/Hybrid-Monte-Carlo#18]
**Aim**
Adapt two tests for the QHO on the lattice 
- `constantEnergy`
- `reversibility`

**Comment by flipdazed** [comment]
- `constantEnergy`: failed
- `reversibility` : passed

**Comment by flipdazed** [comment]
added `pot1d` to plot the energy changes over the steps

**Comment by flipdazed** [comment]
same behaviour for various values of `a`, `step_size` and `n_steps`

**Comment by flipdazed** [comment]
![energy_cons_kg_pot_bug](https://cloud.githubusercontent.com/assets/8991915/16180885/780a3b36-3689-11e6-81ce-96328f25534a.png)
![energy_cons_qho_pot_bug](https://cloud.githubusercontent.com/assets/8991915/16180886/7821dfa2-3689-11e6-8381-c40d1869656e.png)

**Comment by flipdazed** [comment]
Should not be summing over every lattice site! This was an artefact from reusing the code used to write the `potentialEnergy` function:

        # # sum (integrate) across euclidean-space (i.e. all lattice sites)               # ERROR
        # for idx in np.ndindex(lattice.shape):                                           # ERROR
            
        # derivative of velocity squared
        # the derivative of the velocity squared is actually
        # identical to - \klein_gordon^2
        v_sq =  positions.laplacian(idx, a_power=1)
        
        # gradient should be an array of the length of degrees of freedom 
        checks.tryAssertEqual(v_sq.shape, (),
             ' derivative^2 shape should be scalar' \
             + '\n> v_sq shape: {}'.format(v_sq.shape)
             )
        
        # sum to previous                                                                  # ERROR
        v_sq_sum += v_sq                                                                   # ERROR

**Comment by flipdazed** [comment]
![energy_cons_kg_pot_bug](https://cloud.githubusercontent.com/assets/8991915/16202057/0a081d46-370c-11e6-95af-0c19d3a9ab65.png)
![energy_cons_qho_pot_bug](https://cloud.githubusercontent.com/assets/8991915/16202058/0a282794-370c-11e6-9855-ed69143ae94b.png)

**Comment by flipdazed** [comment]
**Reopening**
 1. Hamiltonian is too oscillatory: Was still including the sum of all positions in the `x_sq_sum` variable so replaced with the lattice point at `x = positions.get[idx]`
 2. Need to patch over all the changes made to rip out information for the debugging of this issue.

e.g.
```

 >>> Testing: Lattice dynamics
QHO
 
  Constant Energy
  OUTCOME: Passed
mkdir: ./results/plots/: File exists
Traceback (most recent call last):
  File "test/test_dynamics.py", line 606, in <module>
    print_out = True # shows a small print out)
  File "test/test_dynamics.py", line 460, in reversibility
    pm, xm = self.dynamics.integrate(copy(p0), copy(x0))
  File "/Users/alex/Dropbox/mscTheoPhys/thesis/code/hmc/dynamics.py", line 43, in integrate
    self._storeSteps() # store zeroth step
  File "/Users/alex/Dropbox/mscTheoPhys/thesis/code/hmc/dynamics.py", line 144, in _storeSteps
    self.x_ar.append(copy(self.x.get))
AttributeError: 'numpy.ndarray' object has no attribute 'get'
```

**Comment by flipdazed** [comment]
done
